#!/bin/bash

options=(
    # round or square
	style=round
	width=3.0
	hidpi=on
    ax_focus=on
    # AARRGGBB
	active_color="gradient(top_left=0xff89b4fa,bottom_right=0xff89b4fa)"
	inactive_color=0xff414550
)

borders "${options[@]}"
